// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zteqhpriybjjlqwgmium.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp0ZXFocHJpeWJqamxxd2dtaXVtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4NjQ1NDQsImV4cCI6MjA2NzQ0MDU0NH0.nQOBN7zmucKSX839xQfOEn1eOA6WzN1MFDbb8K0Kt4c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});